@url=http://{{$dotenv HOST}}:{{$dotenv PORT}}/api

### GET /article 
GET {{url}}/article

### POST /article
POST {{url}}/article
content-type: application/json

{
  "barcode": "9475312745450",
  "name": "lot de 3 feutres",
  "brand": "Mapped",
  "price": 100.25
} 

### GET /article/:id
GET {{url}}/article/9
# GET {{url}}/article/3

### PATCH /article/:id
PATCH {{url}}/article/9
content-type: application/json

{
  "brand": "nouvelle chose"
}

### DELETE /article/:id
DELETE {{url}}/article/3

### GET /article/category/:id
GET {{url}}/article/category/2


