@url=http://{{$dotenv HOST}}:{{$dotenv PORT}}/api

### GET /category 
GET {{url}}/category

### POST /category
POST {{url}}/category
content-type: application/json

{
  "name": "jouets pour animaux"
} 

### GET /category/:id
GET {{url}}/category/2
# GET {{url}}/category/3

### PATCH /category/:id
PATCH {{url}}/category/4
content-type: application/json

{
  "name": "ustensile de cuisine"
}

### DELETE /category/:id
DELETE {{url}}/category/4



