@url=http://{{$dotenv HOST}}:{{$dotenv PORT}}/api

### GET /invoice 
GET {{url}}/invoice

### POST /invoice
POST {{url}}/invoice
content-type: application/json

{
  "reference": "INV_0098",
  "total_value": 178.48,
  "customer_id": 1,
  "order_id": 4
} 

### GET /invoice/:id
GET {{url}}/invoice/1

### PATCH /invoice/:id
PATCH {{url}}/invoice/1
content-type: application/json

{
  "total_value": 45.25
} 

### DELETE /invoice/:id
DELETE {{url}}/invoice/20

### GET /invoice/customer/:id
GET {{url}}/invoice/customer/2