@url=http://{{$dotenv HOST}}:{{$dotenv PORT}}/api

### GET /order 
GET {{url}}/order
 
### POST /order
POST {{url}}/order
content-type: application/json

{
  "reference": "OR_0078",
  "value": 104.48,
  "customer_id": 2
} 

### GET /order/:id
GET {{url}}/order/2


### PATCH /order/:id  ! La précision n'est pas validée ! A corriger
PATCH {{url}}/order/2
content-type: application/json

{
  "value": 10.87 
} 

### DELETE /order/:id
DELETE {{url}}/order/4


### GET /order/article/:id
GET {{url}}/order/article/2

### GET /order/customer/:id
GET {{url}}/order/customer/2